config/routes.rb
Rails.application.routes.draw do
  resources :twits

  root 'twits#index'

end

app/models/twit.rb
class Twit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  before_action :set_twit, only: [:show, :edit, :update, :destroy]

  # GET /twits
  # GET /twits.json
  def index
    @twits = Twit.all
  end

  # GET /twits/1
  # GET /twits/1.json
  def show
  end

  # GET /twits/new
  def new
    @twit = Twit.new
  end

  # GET /twits/1/edit
  def edit
  end

  # POST /twits
  # POST /twits.json
  def create
    @twit = Twit.new(twit_params)

    respond_to do |format|
      if @twit.save
        format.html { redirect_to @twit, notice: 'Twit was successfully created.' }
        format.json { render :show, status: :created, location: @twit }
      else
        format.html { render :new }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twits/1
  # PATCH/PUT /twits/1.json
  def update
    respond_to do |format|
      if @twit.update(twit_params)
        format.html { redirect_to @twit, notice: 'Twit was successfully updated.' }
        format.json { render :show, status: :ok, location: @twit }
      else
        format.html { render :edit }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twits/1
  # DELETE /twits/1.json
  def destroy
    @twit.destroy
    respond_to do |format|
      format.html { redirect_to twits_url, notice: 'Twit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twit
      @twit = Twit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twit_params
      params.require(:twit).permit(:title, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twits_helper.rb
module TwitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/twits/_form.html.erb
<%= form_for(@twit) do |f| %>
  <% if @twit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twit.errors.count, "error") %> prohibited this twit from being saved:</h2>

      <ul>
      <% @twit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twits/edit.html.erb
<h1>Editing Twit</h1>

<%= render 'form' %>

<%= link_to 'Show', @twit %> |
<%= link_to 'Back', twits_path %>

app/views/twits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Twits</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @twits.each do |twit| %>
      <tr>
        <td><%= twit.title %></td>
        <td><%= twit.content %></td>
        <td><%= link_to 'Show', twit %></td>
        <td><%= link_to 'Edit', edit_twit_path(twit) %></td>
        <td><%= link_to 'Destroy', twit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twit', new_twit_path %>

app/views/twits/new.html.erb
<h1>New Twit</h1>

<%= render 'form' %>

<%= link_to 'Back', twits_path %>

app/views/twits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @twit.user_id %>
</p>
<p>
  <strong>Title:</strong>
  <%= @twit.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @twit.content %>
</p>

<%= link_to 'Edit', edit_twit_path(@twit) %> |
<%= link_to 'Back', twits_path %>
<%= link_to 'Main Page', root_path %>